App/urls.py
# -*- coding = utf-8 -*-
# @Time : 2020/11/21 17:58
# @Author : Chenih
# @File : urls.py
# @Software : PyCharm


from django.urls import path

from App import views

app_name = 'App'  # 应用名空间，用来反向解析
urlpatterns = [
    path('index/', views.index, name='index'),                            # 首页
    path('login/', views.login, name='login'),                            # 用户登录
    path('loginout/', views.login_out, name='loginout'),                  # 退出登录
    path('userreg/', views.user_register, name='register'),               # 用户注册
    path('del/', views.del_user, name='del'),                             # 用户删除
    path('update/', views.update_user, name='update'),                    # 用户信息更新

    path('showleavingmessage/', views.show_leavingmessage, name='show'),  # 留言板展示
    path('addleavingmessage/', views.add_leavingmessage, name='add'),     # 发表留言
    path('delmessage/', views.del_message, name='delmessage'),            # 删除留言
    path('comment/', views.comment, name='comment'),                      # 留言评论表
    path('showcircular/', views.com_circular, name='circular'),           # 公司通告展示
    path('addcircular/', views.addcircular, name='addcircular'),           # 发布公司通告
    path('delnotice/', views.del_notice, name='delnotice'),                # 删除公司通告

    path('leave_list/', views.leave_list, name='leave_list'),              # 请假人员列表
    path('leave_edit/', views.leave_edit, name='leave_edit'),              # 管理员编辑请假
    path('apply_leave/', views.apply_leave, name='apply_leave'),            # 员工申请假期表
    path('apply/', views.apply, name='apply'),                               # 申请假期
    path('approval/', views.approval, name='approval')                       # 批准假期
]

chenih_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('App.urls'))
]

App/models.py
import datetime

from django.db import models


# 用户表
class User(models.Model):
    username = models.CharField(max_length=20, null=False)
    email = models.CharField(max_length=50, null=False)
    password = models.CharField(max_length=20, null=False)
    address = models.CharField(max_length=50, default='')
    # 一个职位可以有多个员工
    position = models.ForeignKey('Position', on_delete=models.CASCADE, default='')
    department = models.ForeignKey('Department', on_delete=models.CASCADE, default='')
    status = models.BooleanField(choices=((False, 'Not approve'), (True, 'In break')), default=False, verbose_name='Status')

    class Meta:
        db_table = 'user'

# 部门表
class Department(models.Model):
    department_name = models.CharField(max_length=10)

    class Meta:
        db_table = 'department'


# 职位表
class Position(models.Model):
    position = models.CharField(max_length=10)
    # 一个部门可以有多个职位
    department = models.ForeignKey('Department', on_delete=models.CASCADE)

    class Meta:
        db_table = 'position'


# 用户留言表
class LeavingMessage(models.Model):
    content = models.CharField(max_length=200)
    # 添加外键 默认关联User表的用户id
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    addtime = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        db_table = 'leavingmessage'

# 留言评论表
class Comment(models.Model):
    content = models.CharField(max_length=128, verbose_name='内容')
    user = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name='用户')
    leavingmessage = models.ForeignKey('LeavingMessage', on_delete=models.CASCADE, verbose_name='留言')
    time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')

    class Meta:
        db_table = 'comment'

# 公司通知表
class CompanyNotice(models.Model):
    content = models.TextField()
    addtime = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey('User', on_delete=models.CASCADE)


class ApplyLeave(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name='用户')
    reason = models.CharField(max_length=256, verbose_name='请假原因')
    status = models.BooleanField(choices=((False, '审核中'), (True, '已批准')), null=True)
    applydate = models.DateTimeField(auto_now_add=True, verbose_name='申请日期')

templates/addcircular.html
{% extends 'leavingmessage.html' %}
{% block title %}
    <title>Lisa Company Notice(●'◡'●)~-Lisa</title>
{% endblock %}

{% block header %}
    <div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">

            <a class="blog-nav-item" href="/user/showcircular">Company notice</a>
            <a class="blog-nav-item active" href="#">Post notice</a>
            <a class="blog-nav-item" href="/user/index/">Back</a>
            {% if request.session.is_login %}
                <a style="color: yellow" class="blog-nav-item pull-right" href="">{{ request.session.username }}</a>
            {% endif %}
        </nav>
    </div>
    </div>
{% endblock %}

{% block body %}
    <div class="container">

    <div class="blog-header">
        <h1 class="blog-title">The Chenih Companycircular</h1>
        <p class="lead blog-description">Company Notice Office~</p>
    </div>
{#   留言板文本框     #}
        <form action="" method="post">
            {% csrf_token %}
            <textarea class="form-control" rows="8" name="content" placeholder="Please type notice~"></textarea>
            <br>
            <button type="submit" class="btn btn-primary">Post notice</button>
        </form>

    </div>
{% endblock %}

templates/addleavingmessage.html
{% extends 'leavingmessage.html' %}
{% block title %}
    <title>Lisa message board(●'◡'●)~-lisa</title>
{% endblock %}

{% block header %}
    <div class="blog-masthead">
    <div class="container">
        <nav class="blog-nav">

            <a class="blog-nav-item" href="/user/showleavingmessage">Message Board</a>
            <a class="blog-nav-item active" href="#">Post a message</a>
            <a class="blog-nav-item" href="/user/index/">Back</a>
            {% if request.session.is_login %}
                <a style="color: yellow" class="blog-nav-item pull-right" href="">{{ request.session.username }}</a>
            {% endif %}
        </nav>
    </div>
    </div>
{% endblock %}

{% block body %}
    <div class="container">

    <div class="blog-header">
        <h1 class="blog-title">The Lisa Message Board</h1>
        <p class="lead blog-description">A place for employees to express their opinions ~ making friends and relaxing...</p>
    </div>
{#   留言板文本框     #}
        <form action="" method="post">
            {% csrf_token %}
            <textarea class="form-control" rows="8" name="content" placeholder="Speak freely~"></textarea>
            <br>
            <button type="submit" class="btn btn-primary">Post message</button>
        </form>
    </div>


{% endblock %}

templates/apply.html
{% extends 'leave_list.html' %}

{% block title %}
    <span>Apply for leave</span>
{% endblock %}
{% block active %}
<ul class='nav nav-stacked'>
                <li class=''>
                    <a href='{% url 'App:leave_list' %}'>
                        <i class='icon-th'></i>
                        <span>Leave list</span>
                    </a>
                </li>
                <li class='active'>
                    <a href='{% url 'App:apply_leave' %}'>
                        <i class='icon-th'></i>
                        <span>Application leave form</span>
                    </a>
                </li>
            </ul>
{% endblock %}
{% block leavemain %}
    <form class="form-horizontal" method="post" novalidate>
    {% csrf_token %}
  <div class="form-group">
    <label class="col-sm-2 control-label">Employee name</label>
    <div class="col-sm-10">
      <p class="form-control-static">{{ request.session.username }}</p>
    </div>

     <div class="form-group">
    <label class="col-sm-2 control-label">Employee ID</label>
         <input type="text" name="pk" value="{{ request.session.pk }}" placeholder="Please do not modify！！！">
    </div>
  </div>
        <textarea class="form-control" rows="3" placeholder="Please fill in the reason for your leave..." name="reason"></textarea>
        <br>
    <div>
        <button class="btn btn-info right">Submit</button></div>

</form>

{% endblock %}

templates/apply_leave.html
{% extends 'leave_list.html' %}
{% block title %}
    <span>Leave application message</span>
{% endblock %}
{% block active %}
<ul class='nav nav-stacked'>
                <li class=''>
                    <a href='{% url 'App:leave_list' %}'>
                        <i class='icon-th'></i>
                        <span>Leave list</span>
                    </a>
                </li>
                <li class='active'>
                    <a href='{% url 'App:apply_leave' %}'>
                        <i class='icon-th'></i>
                        <span>Application leave form</span>
                    </a>
                </li>
            </ul>
{% endblock %}
{% block leavemain %}
<div class='box-content box-no-padding'>
                                <div class='responsive-table'>
                                    <div class='scrollable-area'>
                                        <table class='data-table-column-filter table table-bordered table-striped'
                                               style='margin-bottom:0;'>
                                            <thead>
                                            <tr>
                                                <th>
                                                    name
                                                </th>
                                                <th>
                                                    leave reason
                                                </th>
                                            <th>
                                                leave time
                                            </th>
                                                <th>
                                                    status
                                                </th>
                                                {% if request.session.pk == 1 %}
                                                <th>operating</th>
                                                {% endif %}
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for apply in applyleaves %}
                                                <tr>
                                                    <td>{{ apply.user.username }}</td>
                                                    <td><a href="" class="__cf_email__"
                                                           data-cfemail="6c0d02180302091818092c040318010d0500420f0301">{{ apply.reason }}</a>
                                                    </td>
                                                    <td>{{ apply.applydate }}</td>
                                                    {% if apply.status == True %}
                                                        <td>
                                                            <span class='label label-success'>{{ apply.get_status_display }}</span>
                                                        </td>

                                                    {% else %}
                                                        <td>
                                                            <span class='label label-important'>{{ apply.get_status_display }}</span>
                                                        </td>

                                                    {% endif %}


                                                    {% if request.session.pk == 1 %}
                                                    <td>
                                                        <div class='text-left'>
                                                            <a class='btn btn-success btn-mini' href='{% url 'App:approval' %}?applyid={{ apply.pk }}&status=True'>
                                                                approval
                                                            </a>
                                                        </div>
                                                    </td>
                                                     {% endif %}
                                                </tr>

                                            {% endfor %}


                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

templates/companycircular.html
{% extends 'leavingmessage.html' %}

{% block title %}
    <title>Lisa message board(●'◡'●)~-lisa</title>
{% endblock %}

{% block header %}
    <div class="blog-masthead">
        <div class="container">
            <nav class="blog-nav">

                <a class="blog-nav-item active" href="#">Company notice</a>
            {% if request.session.pk == 1 %}
                <a class="blog-nav-item" href="/user/addcircular/">Post notice</a>
            {% endif %}
                <a class="blog-nav-item" href="/user/index/">Back</a>
                {% if request.session.is_login %}
                    <a style="color: yellow" class="blog-nav-item pull-right" href="">{{ request.session.username }}</a>
                {% endif %}

            </nav>
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="container">

        <div class="blog-header">
            <h1 class="blog-title">The Lisa Company circular</h1>
            <p class="lead blog-description">Announcement Office!</p>
        </div>
        <div class="row">

            <div class="col-sm-8 blog-main">
                {% for contact in contacts %}

                    <div class="blog-post">
                    <h2 class="blog-post-title" style="font-family: 华文行楷">{{ contact.user.username }}</h2>
                    <p class="blog-post-meta">{{ contact.addtime }}</p>

                    <p>{{ contact.content }}</p>
                    {% if request.session.pk == 1 %}
                    <a class="btn btn-danger glyphicon glyphicon-trash pull-right" href="/user/delnotice/?uid={{ contact.user.id }}&noticeid={{ contact.pk }}">

                    </a>
                    {% endif %}
                    <hr>



                {% endfor %}
                <ul class="pager">
                    <div class="pagination">
                    <span class="step-links">

{#        判断是否有上一页#}
                {% if contacts.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}" class="btn btn-primary">Last page</a>
                {% endif %}

                <span class="current">
                    Page {{ contacts.number }}（{{ contacts.number }}-{{ contacts.paginator.num_pages }}）
                </span>
        {#      判断是否有下一页#}
                {% if contacts.has_next %}
                    <a href="?page={{ contacts.next_page_number }}" class="btn btn-primary">Next page</a>
                {% endif %}
                 </span>
                    </div>
                </ul>
            </div>
                </div><!-- /.blog-main -->

            </div><!-- /.row -->
    </div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Lisa Employee Management System(●'◡'●)~-Lisa</title>
    {% endblock %}
    {% block css %}
        <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/dashboard.css">
    {% endblock %}

</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Lisa Employee Management System</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">


                {% if request.session.is_login %}
                    <li><a href="" style="color: yellow">{{ request.session.username }}</a></li>
                    <li><a href="{% url 'App:loginout' %}">Log out</a></li>

                {% endif %}

            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    {% block left %}
        <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="/user/index/" class="glyphicon glyphicon-home">&nbsp;Dashboard</a></li>
                <li><a href="/user/showleavingmessage/" class="glyphicon glyphicon-pencil">&nbsp;Staff message</a></li>
                <li><a href="/user/showcircular/" class="glyphicon glyphicon-tags">&nbsp;Company notice</a></li>
                <li><a href="{% url 'App:leave_list' %}" class="glyphicon glyphicon-list-alt">&nbsp;Leave list</a></li>
            </ul>

        </div>
    {% endblock %}

    {% block main %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1 class="page-header">Executive introduction</h1>

            <div class="row placeholders">
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="/static/images/wqsy.jpg"
                         width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4>Lisa</h4>
                    <span class="text-muted">CEO</span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="/static/images/timg.jpg"
                         width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4>Wayne</h4>
                    <span class="text-muted">Vice President</span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="/static/images/hdr1.jpg"
                         width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4>Tom</h4>
                    <span class="text-muted">Co-founder</span>
                </div>
                <div class="col-xs-6 col-sm-3 placeholder">
                    <img src="/static/images/fgyy.jpg"
                         width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
                    <h4>Jerry</h4>
                    <span class="text-muted">Co-founder</span>
                </div>
            </div>

            <h2 class="sub-header">employee information</h2>

                    <form role="search" class="navbar-form-custom" action="">
                        <div class="form-group">
                            <input type="text" placeholder="Search by email..." class="form-control" name="top-search" id="top-search">
                        </div>
                    </form>

            <div class="table-responsive">
                <table class="table table-striped table-hover">
                {% if request.session.pk == 1 %}
                    <thead>
                    <tr>
                        <th>Number</th>
                        <th>Employee ID</th>
                        <th>Department</th>
                        <th>Position</th>
                        <th>Email</th>
                        <th>User name</th>
                        <th>Password</th>
                        <th>Address</th>
                        <th>Operating</th>
                    </tr>
                    </thead>
                    <tbody>

                        {% for user in users %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ user.id }}</td>
                            <td>{{ user.position.department.department_name }}</td>
                            <td>{{ user.position.position }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.password }}</td>
                            <td>{{ user.address }}</td>
                            <td>
                                <a class="btn-primary btn-sm glyphicon glyphicon-cog" href="/user/update/?uid={{ user.id }}"></a>
                                <a class="btn-danger btn-sm glyphicon glyphicon-trash" href="/user/del/?uid={{ user.id }}"></a>
                            </td>
                        </tr>
                    {% endfor %}
                        {% else %}
                        <thead>
                    <tr>
                        <th>Number</th>
                        <th>Employee ID</th>
                        <th>Department</th>
                        <th>Position</th>
                        <th>Email</th>
                        <th>User name</th>
                        <th>Password</th>
                        <th>Address</th>
                        <th>Operating</th>
                    </tr>
                    </thead>
                    <tbody>

                        {% for user in users %}



                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ user.id }}</td>
                            <td>{{ user.position.department.department_name }}</td>
                            <td>{{ user.position.position }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.username }}</td>
                            {% if user.pk == request.session.pk %}
                            <td>{{ user.password }}</td>
                            <td>{{ user.address }}</td>
                            <td>
                                <a class="btn-primary btn-sm glyphicon glyphicon-cog" href="/user/update/?uid={{ user.id }}"></a>
                            </td>
                        {% endif %}
                        </tr>

                    {% endfor %}
                    {% endif %}

                    </tbody>
                </table>
            <ul class="pager">
                <div class="pagination">
    <span class="step-links">

{#        判断是否有上一页#}
        {% if users.has_previous %}
            <a href="?page={{ users.previous_page_number }}" class="btn btn-primary">Last Page</a>
        {% endif %}

        <span class="current">
            Page {{ users.number }} （{{ users.number }}-{{ users.paginator.num_pages }}）
        </span>
{#      判断是否有下一页#}
        {% if users.has_next %}
            <a href="?page={{ users.next_page_number }}" class="btn btn-primary">Next Page</a>
        {% endif %}
    </span>
                </div>
            </ul>
            </div>
        </div>
    {% endblock %}
    </div>
</div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>


{#<body>#}

{#    <table border="1">#}
{#        <thead>#}
{#            <tr>#}
{#                <th>序号</th>#}
{#                <th>用户id</th>#}
{#                <th>邮箱</th>#}
{#                <th>用户名</th>#}
{#                <th>操作</th>#}
{#                #}
{#            </tr>#}
{#        </thead>#}
{#        <tbody>#}
{#
{#        </tbody>#}
{#    </table>#}
{#</body>#}
</html>

templates/leave_edit.html
{% extends 'leave_list.html' %}
{% block title %}
    <span>Leave statusedit</span>
{% endblock %}
{% block leavemain %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ userform }}
    <p><button class="btn btn-primary">Submit</button></p>
    </form>
{% endblock %}

templates/login.html
<!DOCTYPE html>
<html lang="zh-CN">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Login丨Lisa</title>
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<body>
<div class="login-container">
    <h1>Lisa Employee Management System</h1>
    <div class="connect">
        <p>Welcome to Lisa Management .</p>
    </div>
    <form action="" method="post" id="loginForm">
        {% csrf_token %}
        <div>
            <input type="text" name="email" class="email" placeholder="email" autocomplete="off"/>
        </div>
        <div>
            <input type="password" name="password" class="password" placeholder="password" oncontextmenu="return false"
                   onpaste="return false"/>
        </div>
        <div>{{ error }}</div>
        <button id="submit" type="submit">Login</button>
    </form>
    <a href="{% url 'App:register' %}">
        <button type="button" class="register-tis">Do not have account?</button>
    </a>
</div>
</body>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'js/supersized-init.js' %}"></script>

</html>





{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Lisa 登录(●'◡'●)~-Lisa </title>#}
{#    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">#}
{#    <link rel="stylesheet" href="/static/css/signin.css">#}
{#</head>#}
{##}
{#<body>#}
{##}
{#<div class="container">#}
{#    <form class="form-signin" action="" method="post">#}
{#        {% csrf_token %}#}
{#        <h2 class="form-signin-heading">请 登 录</h2>#}
{#        <p style="color: red;">{{ msg }}</p>#}
{#        <label for="inputEmail" class="sr-only">邮箱</label>#}
{#        <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">#}
{#        <p style="color: red;">{{ passmsg }}</p>#}
{#        <label for="inputPassword" class="sr-only">密码</label>#}
{#        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="">#}
{##}
{#        {{ error }}#}
{#        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>#}
{#        <br>#}
{#        <a href="{% url 'App:register' %}"><button class="btn btn-lg btn-primary btn-block" type="button">注册</button></a>#}
{#    </form>#}
{##}
{#</div> <!-- /container -->#}
{##}
{#</body>#}
{#</html>#}

templates/user_register.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Chenih注册(●'◡'●)~-chenih</title>#}
{#    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">#}
{#    <link rel="stylesheet" href="/static/css/signin.css">#}
{#</head>#}
{##}
{#<body>#}
{##}
{#<div class="container">#}
{#    <form class="form-signin" action="" method="post">#}
{#        {% csrf_token %}#}
{#        <h2 class="form-signin-heading">请 注 册</h2>#}
{##}
{#        <p style="color: red">{{ msg }}</p>#}
{#        <label for="inputEmail" class="sr-only">邮箱</label>#}
{#        <input name="email" type="email" id="inputEmail" class="form-control" placeholder="请输入邮箱" required=""#}
{#               autofocus="">#}
{##}
{#        <label for="inputUsername" class="sr-only">用户名</label>#}
{#        <input name="username" type="text" id="inputUsername" class="form-control" placeholder="请输入用户名" required="">#}
{##}
{#        <label for="inputPassword" class="sr-only">密码</label>#}
{#        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="请输入密码" required="">#}
{##}
{##}
{#        <label for="inputRePassword" class="sr-only">确认密码</label>#}
{#        <input name="repassword" type="password" id="inputRePassword" class="form-control" placeholder="请确认密码"#}
{#               required="">#}
{##}
{#        部门：#}
{#        <select name="department_id" id="">#}
{#            {% for department in departments %}#}
{#                <option value="{{ department.id }}">{{ department.department_name }}</option>#}
{#            {% endfor %}#}
{#        </select>#}
{##}
{#        职位：#}
{#        <select name="position_id" id="">#}
{#            {% for position in positions %}#}
{#                <option value="{{ position.id }}">{{ position.position }}</option>#}
{#            {% endfor %}#}
{#        </select>#}
{##}
{#        <br>#}
{#        <button class="btn btn-lg btn-primary btn-block" type="submit">注册</button>#}
{#    </form>#}
{#</div> <!-- /container -->#}
{##}
{#</body>#}
{#</html>#}

<!DOCTYPE html>
<html lang="zh-CN">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title>Register丨Lisa</title>
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<body>
<div class="login-container">
    <h1>Lisa Managerment System</h1>
    <div class="connect">
        <p>Welcome to Lisa.</p>
    </div>
    <form action="" method="post" id="loginForm">
        {% csrf_token %}
        <div>
            <input type="text" name="email" class="email" placeholder="email" autocomplete="off"/>
        </div>
        <div>
            <input type="text" name="username" class="username" placeholder="username" autocomplete="off"/>
        </div>
        <div>
            <input type="password" name="password" class="password" placeholder="password" oncontextmenu="return false"
                   onpaste="return false"/>
        </div>
        <div>
            <input type="password" name="repassword" class="password" placeholder="confirm password" autocomplete="off"/>
        </div>

        <select name="department_id" id="">#}
            {% for department in departments %}
                <option value="{{ department.id }}">{{ department.department_name }}</option>
            {% endfor %}
        </select>

        <select name="position_id" id="">
            {% for position in positions %}
                <option value="{{ position.id }}">{{ position.position }}</option>
            {% endfor %}
        </select>


        <div>{{ msg }}</div>
        <button id="submit" type="submit">Register</button>
    </form>
    <a href="{% url 'App:login' %}">
        <button type="button" class="register-tis">Already have account？</button>
    </a>
</div>
</body>


<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/supersized.3.2.7.min.js' %}"></script>
<script src="{% static 'js/supersized-init.js' %}"></script>

</html>